export const AI_MODULE_OPTIONS = 'AI_MODULE_OPTIONS';
export const LLM_PROVIDER = 'LLM_PROVIDER';

export const HIGH_CONFIDENCE_THRESHOLD = 0.9;
export const MEDIUM_CONFIDENCE_THRESHOLD = 0.7;

export const STANDARD_VAT_RATE = '0.2000';
export const ZERO_VAT_RATE = '0.0000';

export enum SemanticCategory {
  // Inventory
  FUEL_INVENTORY = 'FUEL_INVENTORY',
  GENERAL_INVENTORY = 'GENERAL_INVENTORY',
  MATERIALS_INVENTORY = 'MATERIALS_INVENTORY',
  MERCHANDISE_INVENTORY = 'MERCHANDISE_INVENTORY',

  // Sales / Revenue
  FUEL_SALE = 'FUEL_SALE',
  GOODS_SALE = 'GOODS_SALE',
  SERVICE_SALE = 'SERVICE_SALE',

  // Operating Expenses
  SOFTWARE_SUBSCRIPTION = 'SOFTWARE_SUBSCRIPTION',
  CLEANING_EXPENSE = 'CLEANING_EXPENSE',
  UTILITIES_EXPENSE = 'UTILITIES_EXPENSE',
  RENT_EXPENSE = 'RENT_EXPENSE',
  TRAVEL_EXPENSE = 'TRAVEL_EXPENSE',
  PROFESSIONAL_FEES = 'PROFESSIONAL_FEES',
  GENERAL_EXPENSE = 'GENERAL_EXPENSE',

  // Capital / Fixed Assets
  EQUIPMENT_ASSET = 'EQUIPMENT_ASSET',
  VEHICLE_ASSET = 'VEHICLE_ASSET',
  COMPUTER_HARDWARE = 'COMPUTER_HARDWARE',

  // Balance sheet control categories
  ACCOUNTS_PAYABLE = 'ACCOUNTS_PAYABLE',
  ACCOUNTS_RECEIVABLE = 'ACCOUNTS_RECEIVABLE',
  INPUT_VAT = 'INPUT_VAT',
  OUTPUT_VAT = 'OUTPUT_VAT',
}
