import { HttpStatus } from '@nestjs/common';

/**
 * Canonical domain error codes. Every code maps to exactly one HTTP status so
 * clients can rely on `error.code` for programmatic handling.
 */
export const ErrorCodes = {
  // Generic
  VALIDATION_FAILED: HttpStatus.BAD_REQUEST,
  NOT_FOUND: HttpStatus.NOT_FOUND,
  CONFLICT: HttpStatus.CONFLICT,
  CONCURRENT_MODIFICATION: HttpStatus.CONFLICT,
  RATE_LIMITED: HttpStatus.TOO_MANY_REQUESTS,
  INTERNAL_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
  SERVICE_UNAVAILABLE: HttpStatus.SERVICE_UNAVAILABLE,

  // Auth
  AUTH_REQUIRED: HttpStatus.UNAUTHORIZED,
  AUTH_INVALID_CREDENTIALS: HttpStatus.UNAUTHORIZED,
  AUTH_SESSION_EXPIRED: HttpStatus.UNAUTHORIZED,
  AUTH_INVALID_TOKEN: HttpStatus.UNAUTHORIZED,
  AUTH_ACCOUNT_LOCKED: HttpStatus.TOO_MANY_REQUESTS,
  AUTH_ACCOUNT_DISABLED: HttpStatus.FORBIDDEN,
  AUTH_EMAIL_IN_USE: HttpStatus.CONFLICT,
  AUTH_TOKEN_INVALID: HttpStatus.BAD_REQUEST,
  AUTH_WEAK_PASSWORD: HttpStatus.BAD_REQUEST,
  CSRF_TOKEN_INVALID: HttpStatus.FORBIDDEN,
  CSRF_TOKEN_MISSING: HttpStatus.FORBIDDEN,

  // Organisation / access control
  ORGANIZATION_ACCESS_DENIED: HttpStatus.FORBIDDEN,
  ORGANIZATION_INACTIVE: HttpStatus.FORBIDDEN,
  ORGANIZATION_CONTEXT_REQUIRED: HttpStatus.BAD_REQUEST,
  CONFLICTING_ORGANIZATION_CONTEXT: HttpStatus.BAD_REQUEST,
  PERMISSION_DENIED: HttpStatus.FORBIDDEN,
  MEMBER_NOT_FOUND: HttpStatus.NOT_FOUND,
  MEMBER_ALREADY_EXISTS: HttpStatus.CONFLICT,
  LAST_OWNER: HttpStatus.UNPROCESSABLE_ENTITY,
  ROLE_NOT_FOUND: HttpStatus.NOT_FOUND,
  ROLE_PROTECTED: HttpStatus.UNPROCESSABLE_ENTITY,
  DUPLICATE_ROLE_NAME: HttpStatus.CONFLICT,
  PERMISSION_NOT_FOUND: HttpStatus.NOT_FOUND,
  PRIVILEGE_ESCALATION: HttpStatus.FORBIDDEN,
  SUPER_ADMIN_REQUIRED: HttpStatus.FORBIDDEN,
  SUPER_ADMIN_CANNOT_DEMOTE_SELF: HttpStatus.FORBIDDEN,
  CANNOT_REMOVE_LAST_SUPER_ADMIN: HttpStatus.FORBIDDEN,
  CANNOT_SUSPEND_LAST_SUPER_ADMIN: HttpStatus.FORBIDDEN,

  // Chart of accounts
  ACCOUNT_NOT_FOUND: HttpStatus.NOT_FOUND,
  ACCOUNT_ARCHIVED: HttpStatus.UNPROCESSABLE_ENTITY,
  ACCOUNT_MANUAL_POSTING_DISABLED: HttpStatus.UNPROCESSABLE_ENTITY,
  ACCOUNT_PROTECTED: HttpStatus.UNPROCESSABLE_ENTITY,
  ACCOUNT_HAS_HISTORY: HttpStatus.UNPROCESSABLE_ENTITY,
  ACCOUNT_INVALID_CODE: HttpStatus.UNPROCESSABLE_ENTITY,
  ACCOUNT_INVALID_TYPE: HttpStatus.UNPROCESSABLE_ENTITY,
  ACCOUNT_INVALID_PARENT: HttpStatus.UNPROCESSABLE_ENTITY,
  DUPLICATE_ACCOUNT_CODE: HttpStatus.CONFLICT,

  // Financial years & periods
  FINANCIAL_YEAR_NOT_FOUND: HttpStatus.NOT_FOUND,
  FINANCIAL_YEAR_OVERLAP: HttpStatus.CONFLICT,
  FINANCIAL_YEAR_INVALID_RANGE: HttpStatus.UNPROCESSABLE_ENTITY,
  FINANCIAL_YEAR_CLOSED: HttpStatus.UNPROCESSABLE_ENTITY,
  FINANCIAL_YEAR_HAS_PERIODS: HttpStatus.CONFLICT,
  PERIOD_NOT_FOUND: HttpStatus.UNPROCESSABLE_ENTITY,
  PERIOD_SOFT_LOCKED: HttpStatus.UNPROCESSABLE_ENTITY,
  PERIOD_HARD_LOCKED: HttpStatus.UNPROCESSABLE_ENTITY,
  PERIOD_INVALID_TRANSITION: HttpStatus.UNPROCESSABLE_ENTITY,

  // Journals
  JOURNAL_NOT_FOUND: HttpStatus.NOT_FOUND,
  JOURNAL_INVALID_STATE: HttpStatus.CONFLICT,
  JOURNAL_UNBALANCED: HttpStatus.UNPROCESSABLE_ENTITY,
  JOURNAL_INSUFFICIENT_LINES: HttpStatus.UNPROCESSABLE_ENTITY,
  JOURNAL_LINE_NOT_FOUND: HttpStatus.NOT_FOUND,
  JOURNAL_TOO_MANY_LINES: HttpStatus.UNPROCESSABLE_ENTITY,
  JOURNAL_CURRENCY_INVALID: HttpStatus.UNPROCESSABLE_ENTITY,
  UNSUPPORTED_CURRENCY: HttpStatus.UNPROCESSABLE_ENTITY,
  CURRENCY_MISMATCH: HttpStatus.UNPROCESSABLE_ENTITY,
  JOURNAL_DUPLICATE_IDEMPOTENCY_KEY: HttpStatus.CONFLICT,
  JOURNAL_ALREADY_POSTED: HttpStatus.CONFLICT,
  JOURNAL_ALREADY_REVERSED: HttpStatus.CONFLICT,
  JOURNAL_NOT_VALIDATED: HttpStatus.BAD_REQUEST,
  JOURNAL_SYSTEM_MANAGED: HttpStatus.CONFLICT,
  JOURNAL_INVALID_STATUS_FOR_REVERSAL: HttpStatus.BAD_REQUEST,
  POSTING_VALIDATION_FAILED: HttpStatus.UNPROCESSABLE_ENTITY,
  POSTING_PERIOD_INVALID: HttpStatus.UNPROCESSABLE_ENTITY,
  REVERSAL_PERIOD_INVALID: HttpStatus.UNPROCESSABLE_ENTITY,
  ACCOUNT_INACTIVE: HttpStatus.BAD_REQUEST,

  // Contacts
  CONTACT_NOT_FOUND: HttpStatus.NOT_FOUND,
  CONTACT_ARCHIVED: HttpStatus.UNPROCESSABLE_ENTITY,
  CONTACT_INVALID_TYPE: HttpStatus.BAD_REQUEST,

  // Invoices
  INVOICE_NOT_FOUND: HttpStatus.NOT_FOUND,
  INVOICE_INVALID_STATE: HttpStatus.CONFLICT,
  INVOICE_ALREADY_POSTED: HttpStatus.CONFLICT,
  INVOICE_ALREADY_VOIDED: HttpStatus.CONFLICT,
  INVOICE_CANNOT_VOID: HttpStatus.BAD_REQUEST,
  INVOICE_NO_LINES: HttpStatus.UNPROCESSABLE_ENTITY,
  INVOICE_INVALID_LINE: HttpStatus.UNPROCESSABLE_ENTITY,
  INVOICE_MISSING_CUSTOMER: HttpStatus.BAD_REQUEST,
} as const satisfies Record<string, HttpStatus>;

export type ErrorCode = keyof typeof ErrorCodes;

/** Business-rule failure raised by services; translated by the global exception filter. */
export class DomainException extends Error {
  readonly status: HttpStatus;

  constructor(
    readonly code: ErrorCode,
    message: string,
    readonly details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = 'DomainException';
    this.status = ErrorCodes[code];
  }
}

export const notFound = (code: ErrorCode, entity: string): DomainException =>
  new DomainException(code, `${entity} was not found`);
