export const AuditEvents = {
  // Auth (organisation-less)
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_LOGOUT: 'USER_LOGOUT',
  SESSION_REVOKED: 'SESSION_REVOKED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',

  // Organisation
  ORGANIZATION_CREATED: 'ORGANIZATION_CREATED',
  ORGANIZATION_UPDATED: 'ORGANIZATION_UPDATED',
  ORGANIZATION_ARCHIVED: 'ORGANIZATION_ARCHIVED',
  ORGANIZATION_SWITCHED: 'ORGANIZATION_SWITCHED',
  USER_INVITED: 'USER_INVITED',
  MEMBER_REMOVED: 'MEMBER_REMOVED',
  ROLE_CHANGED: 'ROLE_CHANGED',
  ROLE_CREATED: 'ROLE_CREATED',
  ROLE_UPDATED: 'ROLE_UPDATED',
  PERMISSION_GRANTED: 'PERMISSION_GRANTED',
  PERMISSION_REVOKED: 'PERMISSION_REVOKED',

  // Chart of accounts
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  ACCOUNT_UPDATED: 'ACCOUNT_UPDATED',
  ACCOUNT_ARCHIVED: 'ACCOUNT_ARCHIVED',
  ACCOUNT_RESTORED: 'ACCOUNT_RESTORED',
  CHART_OF_ACCOUNTS_TEMPLATE_APPLIED: 'CHART_OF_ACCOUNTS_TEMPLATE_APPLIED',

  // Financial years & periods
  FINANCIAL_YEAR_CREATED: 'FINANCIAL_YEAR_CREATED',
  FINANCIAL_YEAR_UPDATED: 'FINANCIAL_YEAR_UPDATED',
  PERIOD_CREATED: 'PERIOD_CREATED',
  PERIOD_LOCKED: 'PERIOD_LOCKED',
  PERIOD_SOFT_LOCKED: 'PERIOD_SOFT_LOCKED',
  PERIOD_HARD_LOCKED: 'PERIOD_HARD_LOCKED',
  PERIOD_UNLOCKED: 'PERIOD_UNLOCKED',

  // Journals
  JOURNAL_CREATED: 'JOURNAL_CREATED',
  JOURNAL_UPDATED: 'JOURNAL_UPDATED',
  JOURNAL_DELETED_DRAFT: 'JOURNAL_DELETED_DRAFT',
  JOURNAL_VALIDATED: 'JOURNAL_VALIDATED',
  JOURNAL_VALIDATION_FAILED: 'JOURNAL_VALIDATION_FAILED',
  JOURNAL_POSTED: 'JOURNAL_POSTED',
  JOURNAL_REVERSAL_CREATED: 'JOURNAL_REVERSAL_CREATED',
  JOURNAL_REVERSED: 'JOURNAL_REVERSED',

  // Contacts
  CONTACT_CREATED: 'CONTACT_CREATED',
  CONTACT_UPDATED: 'CONTACT_UPDATED',
  CONTACT_ARCHIVED: 'CONTACT_ARCHIVED',
  CONTACT_RESTORED: 'CONTACT_RESTORED',

  // Invoices
  INVOICE_CREATED: 'INVOICE_CREATED',
  INVOICE_UPDATED: 'INVOICE_UPDATED',
  INVOICE_DELETED_DRAFT: 'INVOICE_DELETED_DRAFT',
  INVOICE_POSTED: 'INVOICE_POSTED',
  INVOICE_VOIDED: 'INVOICE_VOIDED',

  // System & Accounting Integrity
  ACCOUNTING_INTEGRITY_CHECK_RUN: 'ACCOUNTING_INTEGRITY_CHECK_RUN',
} as const;

export type AuditEventType = (typeof AuditEvents)[keyof typeof AuditEvents];
